### ISSUE TITLE
Enlace erróneo

### ISSUE THREAD

**Issue by victorhck** [Ondiz/ogibero#2]
Hola!

En enlace a la web "panarras" de la sección Beliabideak está mál direccionado.
El enlace apunta a: https://ondiz.github.io/ogibero/baliabideak/www.panarras.com
Lo que lleva a una flamante 404 :)

Saludos.

**Comment by Ondiz** [comment]
Cierto! Faltaba el http :smile: 

Corregido en 20bb595602d190bd6bcbc201509f5584a5f320fe

Mila esker!
